<?php
//000000000600a:5:{i:0;a:14:{s:2:"id";i:251;s:7:"content";s:12:"100;2;zheshi";s:11:"create_time";i:1463660653;s:4:"type";s:4:"feed";s:4:"data";a:0:{}s:10:"weibo_data";a:0:{}s:13:"comment_count";i:1;s:12:"repost_count";i:0;s:10:"can_delete";b:0;s:6:"is_top";s:1:"0";s:3:"uid";s:1:"1";s:12:"fetchContent";s:38:"<p class='word-wrap'>100;2;zheshi</p> ";s:4:"from";s:0:"";s:4:"user";a:7:{s:3:"uid";s:1:"1";s:8:"nickname";s:5:"admin";s:8:"avatar64";s:54:"/opensnseclipse/Public/images/default_avatar_64_64.jpg";s:9:"space_url";s:59:"/opensnseclipse/index.php?s=/ucenter/index/index/uid/1.html";s:9:"rank_link";a:0:{}s:5:"title";s:10:"Lv1 实习";s:13:"real_nickname";s:5:"admin";}}i:1;a:14:{s:2:"id";i:250;s:7:"content";s:15:"转发发微博";s:11:"create_time";i:1463646338;s:4:"type";s:6:"repost";s:4:"data";a:2:{s:6:"source";N;s:8:"sourceId";i:249;}s:10:"weibo_data";a:2:{s:6:"source";N;s:8:"sourceId";i:249;}s:13:"comment_count";i:5;s:12:"repost_count";i:0;s:10:"can_delete";b:0;s:6:"is_top";s:1:"1";s:3:"uid";s:1:"1";s:12:"fetchContent";s:1287:"    <p class="word-wrap">转发发微博</p>

    <div class="triangle sanjiao" style="margin-left: 20px;border-bottom: 10px solid #e8e8e8;"></div>
    <div class="triangle_up sanjiao" style="margin-left: 20px;border-bottom: 10px solid #f1f1f1;"></div>
    <div  style="border: 1px solid #e8e8e8;padding: 10px;margin-bottom: 20px; background: #f1f1f1">
            <div>  <a ucard="1"     href="/opensnseclipse/index.php?s=/ucenter/index/index/uid/1.html">@admin</a></div>
        <p class='word-wrap'>发微博</p>         <span class="text-primary pull-left" style="font-size: 12px;"><a href="/opensnseclipse/index.php?s=/weibo/index/weibodetail/id/249.html">05月19日 16:25</a>   </span>
        <span class="text-primary pull-right" style="font-size: 12px;"><a href="/opensnseclipse/index.php?s=/weibo/index/weibodetail/id/249.html"> 原微博转发（1）</a>  </span>
        &nbsp;    </div>
    <script>
            var html='<a href="/opensnseclipse/index.php?s=/ucenter/index/index/uid/1.html" ucard="1" style="position: absolute;margin-top: 32px;margin-left: -32px;"><img src="/opensnseclipse/Public/images/default_avatar_32_32.jpg"   class="avatar-img"   style="width: 32px;"/> </a>';
            $('#weibo_250').find('.s_avatar').after(html);
        </script> ";s:4:"from";s:0:"";s:4:"user";a:7:{s:3:"uid";s:1:"1";s:8:"nickname";s:5:"admin";s:8:"avatar64";s:54:"/opensnseclipse/Public/images/default_avatar_64_64.jpg";s:9:"space_url";s:59:"/opensnseclipse/index.php?s=/ucenter/index/index/uid/1.html";s:9:"rank_link";a:0:{}s:5:"title";s:10:"Lv1 实习";s:13:"real_nickname";s:5:"admin";}}i:2;a:14:{s:2:"id";i:249;s:7:"content";s:9:"发微博";s:11:"create_time";i:1463646316;s:4:"type";s:4:"feed";s:4:"data";a:0:{}s:10:"weibo_data";a:0:{}s:13:"comment_count";i:2;s:12:"repost_count";i:1;s:10:"can_delete";b:0;s:6:"is_top";s:1:"0";s:3:"uid";s:1:"1";s:12:"fetchContent";s:35:"<p class='word-wrap'>发微博</p> ";s:4:"from";s:0:"";s:4:"user";a:7:{s:3:"uid";s:1:"1";s:8:"nickname";s:5:"admin";s:8:"avatar64";s:54:"/opensnseclipse/Public/images/default_avatar_64_64.jpg";s:9:"space_url";s:59:"/opensnseclipse/index.php?s=/ucenter/index/index/uid/1.html";s:9:"rank_link";a:0:{}s:5:"title";s:10:"Lv1 实习";s:13:"real_nickname";s:5:"admin";}}i:3;a:14:{s:2:"id";i:247;s:7:"content";s:4:"post";s:11:"create_time";i:1463643023;s:4:"type";s:4:"feed";s:4:"data";a:0:{}s:10:"weibo_data";a:0:{}s:13:"comment_count";i:0;s:12:"repost_count";i:0;s:10:"can_delete";b:0;s:6:"is_top";s:1:"1";s:3:"uid";s:3:"120";s:12:"fetchContent";s:30:"<p class='word-wrap'>post</p> ";s:4:"from";s:0:"";s:4:"user";a:1:{s:13:"real_nickname";N;}}i:4;a:14:{s:2:"id";i:240;s:7:"content";s:30:"post//@admin：转发源微博";s:11:"create_time";i:1463625851;s:4:"type";s:6:"repost";s:4:"data";a:2:{s:6:"source";N;s:8:"sourceId";s:3:"230";}s:10:"weibo_data";a:2:{s:6:"source";N;s:8:"sourceId";s:3:"230";}s:13:"comment_count";i:0;s:12:"repost_count";i:0;s:10:"can_delete";b:0;s:6:"is_top";s:1:"1";s:3:"uid";s:3:"100";s:12:"fetchContent";s:1302:"    <p class="word-wrap">post//@admin：转发源微博</p>

    <div class="triangle sanjiao" style="margin-left: 20px;border-bottom: 10px solid #e8e8e8;"></div>
    <div class="triangle_up sanjiao" style="margin-left: 20px;border-bottom: 10px solid #f1f1f1;"></div>
    <div  style="border: 1px solid #e8e8e8;padding: 10px;margin-bottom: 20px; background: #f1f1f1">
            <div>  <a ucard="1"     href="/opensnseclipse/index.php?s=/ucenter/index/index/uid/1.html">@admin</a></div>
        <p class='word-wrap'>源微博</p>         <span class="text-primary pull-left" style="font-size: 12px;"><a href="/opensnseclipse/index.php?s=/weibo/index/weibodetail/id/230.html">05月19日 09:45</a>   </span>
        <span class="text-primary pull-right" style="font-size: 12px;"><a href="/opensnseclipse/index.php?s=/weibo/index/weibodetail/id/230.html"> 原微博转发（7）</a>  </span>
        &nbsp;    </div>
    <script>
            var html='<a href="/opensnseclipse/index.php?s=/ucenter/index/index/uid/1.html" ucard="1" style="position: absolute;margin-top: 32px;margin-left: -32px;"><img src="/opensnseclipse/Public/images/default_avatar_32_32.jpg"   class="avatar-img"   style="width: 32px;"/> </a>';
            $('#weibo_240').find('.s_avatar').after(html);
        </script> ";s:4:"from";s:0:"";s:4:"user";a:7:{s:3:"uid";s:3:"100";s:8:"nickname";s:6:"刘祥";s:8:"avatar64";s:54:"/opensnseclipse/Public/images/default_avatar_64_64.jpg";s:9:"space_url";s:61:"/opensnseclipse/index.php?s=/ucenter/index/index/uid/100.html";s:9:"rank_link";a:0:{}s:5:"title";s:10:"Lv1 实习";s:13:"real_nickname";s:6:"刘祥";}}}
?>