<?php
//000000000600a:5:{i:0;a:14:{s:2:"id";i:2;s:7:"content";s:15:"上帝给时代";s:11:"create_time";i:1463147805;s:4:"type";s:6:"repost";s:4:"data";a:2:{s:6:"source";N;s:8:"sourceId";i:1;}s:10:"weibo_data";a:2:{s:6:"source";N;s:8:"sourceId";i:1;}s:13:"comment_count";i:2;s:12:"repost_count";i:2;s:10:"can_delete";b:0;s:6:"is_top";s:1:"0";s:3:"uid";s:1:"1";s:12:"fetchContent";s:1610:"    <p class="word-wrap">上帝给时代</p>

    <div class="triangle sanjiao" style="margin-left: 20px;border-bottom: 10px solid #e8e8e8;"></div>
    <div class="triangle_up sanjiao" style="margin-left: 20px;border-bottom: 10px solid #f1f1f1;"></div>
    <div  style="border: 1px solid #e8e8e8;padding: 10px;margin-bottom: 20px; background: #f1f1f1">
            <div>  <a ucard="1"     href="/opensnseclipse/index.php?s=/ucenter/index/index/uid/1.html">@admin</a></div>
        <p class='word-wrap'>opensnseclipse写微博，哈哈哈哈哈哈哈哈，楼欧欧欧欧欧欧欧欧欧欧欧欧欧欧哦欧。第一篇 opensnseclipse写微博，哈哈哈哈哈哈哈哈，楼欧欧欧欧欧欧欧欧欧欧欧欧欧欧哦欧。第一篇 opensnseclipse写微博，哈哈哈哈哈哈哈哈，楼欧欧欧欧欧欧欧欧欧欧欧欧欧欧</p>         <span class="text-primary pull-left" style="font-size: 12px;"><a href="/opensnseclipse/index.php?s=/weibo/index/weibodetail/id/1.html">05月08日 12:08</a>   </span>
        <span class="text-primary pull-right" style="font-size: 12px;"><a href="/opensnseclipse/index.php?s=/weibo/index/weibodetail/id/1.html"> 原网站主页转发（4）</a>  </span>
        &nbsp;    </div>
    <script>
            var html='<a href="/opensnseclipse/index.php?s=/ucenter/index/index/uid/1.html" ucard="1" style="position: absolute;margin-top: 32px;margin-left: -32px;"><img src="/opensnseclipse/Public/images/default_avatar_32_32.jpg"   class="avatar-img"   style="width: 32px;"/> </a>';
            $('#weibo_2').find('.s_avatar').after(html);
        </script> ";s:4:"from";s:0:"";s:4:"user";a:7:{s:3:"uid";s:1:"1";s:8:"nickname";s:5:"admin";s:8:"avatar64";s:54:"/opensnseclipse/Public/images/default_avatar_64_64.jpg";s:9:"space_url";s:59:"/opensnseclipse/index.php?s=/ucenter/index/index/uid/1.html";s:9:"rank_link";a:0:{}s:5:"title";s:10:"Lv1 实习";s:13:"real_nickname";s:5:"admin";}}i:1;a:14:{s:2:"id";i:1;s:7:"content";s:332:"opensnseclipse写微博，哈哈哈哈哈哈哈哈，楼欧欧欧欧欧欧欧欧欧欧欧欧欧欧哦欧。第一篇 opensnseclipse写微博，哈哈哈哈哈哈哈哈，楼欧欧欧欧欧欧欧欧欧欧欧欧欧欧哦欧。第一篇 opensnseclipse写微博，哈哈哈哈哈哈哈哈，楼欧欧欧欧欧欧欧欧欧欧欧欧欧欧";s:11:"create_time";i:1462680511;s:4:"type";s:4:"feed";s:4:"data";a:0:{}s:10:"weibo_data";a:0:{}s:13:"comment_count";i:0;s:12:"repost_count";i:4;s:10:"can_delete";b:0;s:6:"is_top";s:1:"0";s:3:"uid";s:1:"1";s:12:"fetchContent";s:358:"<p class='word-wrap'>opensnseclipse写微博，哈哈哈哈哈哈哈哈，楼欧欧欧欧欧欧欧欧欧欧欧欧欧欧哦欧。第一篇 opensnseclipse写微博，哈哈哈哈哈哈哈哈，楼欧欧欧欧欧欧欧欧欧欧欧欧欧欧哦欧。第一篇 opensnseclipse写微博，哈哈哈哈哈哈哈哈，楼欧欧欧欧欧欧欧欧欧欧欧欧欧欧</p> ";s:4:"from";s:0:"";s:4:"user";a:7:{s:3:"uid";s:1:"1";s:8:"nickname";s:5:"admin";s:8:"avatar64";s:54:"/opensnseclipse/Public/images/default_avatar_64_64.jpg";s:9:"space_url";s:59:"/opensnseclipse/index.php?s=/ucenter/index/index/uid/1.html";s:9:"rank_link";a:0:{}s:5:"title";s:10:"Lv1 实习";s:13:"real_nickname";s:5:"admin";}}i:2;a:14:{s:2:"id";i:5;s:7:"content";s:41:"删除后转发//@admin：上帝给时代";s:11:"create_time";i:1463277534;s:4:"type";s:6:"repost";s:4:"data";a:2:{s:6:"source";N;s:8:"sourceId";i:1;}s:10:"weibo_data";a:2:{s:6:"source";N;s:8:"sourceId";i:1;}s:13:"comment_count";i:0;s:12:"repost_count";i:1;s:10:"can_delete";b:0;s:6:"is_top";s:1:"0";s:3:"uid";s:1:"1";s:12:"fetchContent";s:1636:"    <p class="word-wrap">删除后转发//@admin：上帝给时代</p>

    <div class="triangle sanjiao" style="margin-left: 20px;border-bottom: 10px solid #e8e8e8;"></div>
    <div class="triangle_up sanjiao" style="margin-left: 20px;border-bottom: 10px solid #f1f1f1;"></div>
    <div  style="border: 1px solid #e8e8e8;padding: 10px;margin-bottom: 20px; background: #f1f1f1">
            <div>  <a ucard="1"     href="/opensnseclipse/index.php?s=/ucenter/index/index/uid/1.html">@admin</a></div>
        <p class='word-wrap'>opensnseclipse写微博，哈哈哈哈哈哈哈哈，楼欧欧欧欧欧欧欧欧欧欧欧欧欧欧哦欧。第一篇 opensnseclipse写微博，哈哈哈哈哈哈哈哈，楼欧欧欧欧欧欧欧欧欧欧欧欧欧欧哦欧。第一篇 opensnseclipse写微博，哈哈哈哈哈哈哈哈，楼欧欧欧欧欧欧欧欧欧欧欧欧欧欧</p>         <span class="text-primary pull-left" style="font-size: 12px;"><a href="/opensnseclipse/index.php?s=/weibo/index/weibodetail/id/1.html">05月08日 12:08</a>   </span>
        <span class="text-primary pull-right" style="font-size: 12px;"><a href="/opensnseclipse/index.php?s=/weibo/index/weibodetail/id/1.html"> 原网站主页转发（4）</a>  </span>
        &nbsp;    </div>
    <script>
            var html='<a href="/opensnseclipse/index.php?s=/ucenter/index/index/uid/1.html" ucard="1" style="position: absolute;margin-top: 32px;margin-left: -32px;"><img src="/opensnseclipse/Public/images/default_avatar_32_32.jpg"   class="avatar-img"   style="width: 32px;"/> </a>';
            $('#weibo_5').find('.s_avatar').after(html);
        </script> ";s:4:"from";s:0:"";s:4:"user";a:7:{s:3:"uid";s:1:"1";s:8:"nickname";s:5:"admin";s:8:"avatar64";s:54:"/opensnseclipse/Public/images/default_avatar_64_64.jpg";s:9:"space_url";s:59:"/opensnseclipse/index.php?s=/ucenter/index/index/uid/1.html";s:9:"rank_link";a:0:{}s:5:"title";s:10:"Lv1 实习";s:13:"real_nickname";s:5:"admin";}}i:3;a:14:{s:2:"id";i:121;s:7:"content";s:36:"开一篇新微博，转发使用。";s:11:"create_time";i:1463383921;s:4:"type";s:4:"feed";s:4:"data";a:0:{}s:10:"weibo_data";a:0:{}s:13:"comment_count";i:0;s:12:"repost_count";i:9;s:10:"can_delete";b:0;s:6:"is_top";s:1:"0";s:3:"uid";s:1:"1";s:12:"fetchContent";s:62:"<p class='word-wrap'>开一篇新微博，转发使用。</p> ";s:4:"from";s:0:"";s:4:"user";a:7:{s:3:"uid";s:1:"1";s:8:"nickname";s:5:"admin";s:8:"avatar64";s:54:"/opensnseclipse/Public/images/default_avatar_64_64.jpg";s:9:"space_url";s:59:"/opensnseclipse/index.php?s=/ucenter/index/index/uid/1.html";s:9:"rank_link";a:0:{}s:5:"title";s:10:"Lv1 实习";s:13:"real_nickname";s:5:"admin";}}i:4;a:14:{s:2:"id";i:149;s:7:"content";s:52:"//@admin：删除后转发//@admin：上帝给时代";s:11:"create_time";i:1463404988;s:4:"type";s:6:"repost";s:4:"data";a:2:{s:6:"source";N;s:8:"sourceId";i:1;}s:10:"weibo_data";a:2:{s:6:"source";N;s:8:"sourceId";i:1;}s:13:"comment_count";i:0;s:12:"repost_count";i:1;s:10:"can_delete";b:0;s:6:"is_top";s:1:"0";s:3:"uid";s:1:"1";s:12:"fetchContent";s:1649:"    <p class="word-wrap">//@admin：删除后转发//@admin：上帝给时代</p>

    <div class="triangle sanjiao" style="margin-left: 20px;border-bottom: 10px solid #e8e8e8;"></div>
    <div class="triangle_up sanjiao" style="margin-left: 20px;border-bottom: 10px solid #f1f1f1;"></div>
    <div  style="border: 1px solid #e8e8e8;padding: 10px;margin-bottom: 20px; background: #f1f1f1">
            <div>  <a ucard="1"     href="/opensnseclipse/index.php?s=/ucenter/index/index/uid/1.html">@admin</a></div>
        <p class='word-wrap'>opensnseclipse写微博，哈哈哈哈哈哈哈哈，楼欧欧欧欧欧欧欧欧欧欧欧欧欧欧哦欧。第一篇 opensnseclipse写微博，哈哈哈哈哈哈哈哈，楼欧欧欧欧欧欧欧欧欧欧欧欧欧欧哦欧。第一篇 opensnseclipse写微博，哈哈哈哈哈哈哈哈，楼欧欧欧欧欧欧欧欧欧欧欧欧欧欧</p>         <span class="text-primary pull-left" style="font-size: 12px;"><a href="/opensnseclipse/index.php?s=/weibo/index/weibodetail/id/1.html">05月08日 12:08</a>   </span>
        <span class="text-primary pull-right" style="font-size: 12px;"><a href="/opensnseclipse/index.php?s=/weibo/index/weibodetail/id/1.html"> 原网站主页转发（4）</a>  </span>
        &nbsp;    </div>
    <script>
            var html='<a href="/opensnseclipse/index.php?s=/ucenter/index/index/uid/1.html" ucard="1" style="position: absolute;margin-top: 32px;margin-left: -32px;"><img src="/opensnseclipse/Public/images/default_avatar_32_32.jpg"   class="avatar-img"   style="width: 32px;"/> </a>';
            $('#weibo_149').find('.s_avatar').after(html);
        </script> ";s:4:"from";s:0:"";s:4:"user";a:7:{s:3:"uid";s:1:"1";s:8:"nickname";s:5:"admin";s:8:"avatar64";s:54:"/opensnseclipse/Public/images/default_avatar_64_64.jpg";s:9:"space_url";s:59:"/opensnseclipse/index.php?s=/ucenter/index/index/uid/1.html";s:9:"rank_link";a:0:{}s:5:"title";s:10:"Lv1 实习";s:13:"real_nickname";s:5:"admin";}}}
?>